# Generated by Django 3.1.6 on 2021-04-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone', models.SmallIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('group', models.CharField(choices=[('A+', 'A+'), ('AB+', 'AB+'), ('B+', 'B+'), ('O+', 'O+'), ('A-', 'A-'), ('AB-', 'AB-'), ('B-', 'B-'), ('O-', 'O-')], default='A+', max_length=5)),
                ('province', models.CharField(max_length=100)),
                ('municipe', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest', models.CharField(max_length=9)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=500)),
            ],
        ),
    ]
