# Generated by Django 3.1.6 on 2021-04-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
